name: basic-python-workflow
on: [push, pull_request]
jobs:
  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Run unit tests
        run: |
          poetry run python -m pytest
      - name: flake8 validation
        run: |
          poetry run python -m flake8 .
      - name: isort validation
        run: |
          poetry run python -m isort . --check-only
      - name: black validation
        run: |
          poetry run python -m black . -l 79 -S --check
