name: basic-python-workflow
on: [push, pull_request]
jobs:

  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check -l 79 -S"

  test:
    name: Test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Installing dependencies
        run: |
          poetry install
      - name: Running tests
        run: |
          poetry run pytest
